### ISSUE TITLE
Adding the sample config just causes HA check config to spin and spin

### ISSUE THREAD

**Issue by dcmeglio** [gaggle331/home-assistant-kevo#13]
After installing the integration via HACS I added:

```
lock:
  - platform: kevo_plus
    email: USER
    password: PWD
    locks:
      - lock_id: ID
        max_retries: 3
        retry_delay: 2
```

As soon as I add this the Check Configuration button just spins and spins and never says my config is valid nor reports an error.  I'm new to HA, is this sample config still valid in 2022.6.4?
